server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
